# this is a required setting for this theme to appear on https://themes.gohugo.io/
# change this to a value appropriate for you; if your site is served from a subdirectory
# set it like "https://example.com/mysite/"
baseURL = 'http://d4d0o.github.io/latannerie/'

# canonicalization will only be used for the sitemap.xml and index.xml files;
# if set to false, a site served from a subdirectory will generate wrong links
# inside of the above mentioned files; if you serve the page from the servers root
# you are free to set the value to false as recommended by the official Hugo documentation
canonifyURLs = false # true -> all relative URLs would instead be canonicalized using baseURL
# required value to serve this page from a webserver AND the file system;
# if you don't want to serve your page from the file system, you can also set this value
# to false
relativeURLs = true # true -> rewrite all relative URLs to be relative to the current content
# if you set uglyURLs to false, this theme will append 'index.html' to any branch bundle link
# so your page can be also served from the file system; if you don't want that,
# set disableExplicitIndexURLs=true in the [params] section
uglyURLs = false     # true -> basic/index.html -> basic.html


# Change the default theme to be use when building the site with Hugo
theme = "hugo-theme-relearn"


# the main language of this site
languageCode = "fr"
# make sure your defaultContentLanguage is the first one in the [languages]
# array below, as the theme needs to make assumptions on it
defaultContentLanguage = "fr"

[languages]
  [languages.fr]
    title = "La Tannerie"
    weight = 1
    languageName = "Français"
    [languages.fr.params]
      landingPageName = "<i class='fas fa-home'></i>"

  [languages.en]
    title = "La Tannerie"
    weight = 2
    languageName = "English"
    [languages.en.params]
      landingPageName = "<i class='fas fa-home'></i>"

[outputs]
  # add JSON to the home to support Lunr search; This is a mandatory setting
  # for the search functionality
  # add PRINT to home, section and page to activate the feature to print whole
  # chapters
  home = ["HTML", "RSS", "PRINT", "SEARCH", "SEARCHPAGE"]
  section = ["HTML", "RSS", "PRINT"]
  page = ["HTML", "RSS", "PRINT"]

[markup]
  [markup.highlight]
    # line numbers in a table layout will shift if code is wrapping, so better
    # not use it; visually both layouts have the same look and behavior
    lineNumbersInTable = false

    # if `guessSyntax = true`, there will be no unstyled code even if no language
    # was given BUT Mermaid and Math codefences will not work anymore! So this is a
    # mandatory setting for your site if you want to use Mermaid or Math codefences
    guessSyntax = false

    # the shipped variants come with their own modified chroma syntax highlightning
    # style which is imported in theme-relearn-light.css, theme-relearn-dark.css, etc.;
    # if you want to use a predefined style instead:
    # - remove `noClasses` or set `noClasses = true`
    # - set `style` to a predefined style name
    noClasses = false
    # style = "tango"

# settings specific to this theme's features; choose to your likings and
# consult this documentation for explaination
[params]
  #editURL = "https://github.com/McShelby/hugo-theme-relearn/edit/main/exampleSite/content/"
  description = "Guide de l'Habitant à La Tannerie"
  author = "David Peter"
  showVisitedLinks = false
  collapsibleMenu = true
  disableBreadcrumb = false
  disableRootBreadcrumb = true
  disableInlineCopyToClipBoard = true
  disableNextPrev = false
  disableLandingPageButton = true
  breadcrumbSeparator = ">"
  titleSeparator = "::"
  themeVariant = [ "auto", "relearn-bright", "relearn-light", "relearn-dark", "zen-light", "zen-dark", "neon", "learn", "blue", "green", "red" ]
  themeVariantAuto = [ "relearn-light", "relearn-dark" ]
  disableSeoHiddenPages = true
  # this is to index search for your native language in other languages, too (eg.
  # pir in this showcase)
  additionalContentLanguage = [ "en" ]
  # this is for the stylesheet generator to allow for interactivity in Mermaid
  # graphs; you usually will not need it and you should remove this for
  # security reasons
  mermaidInitialize = "{ \"securityLevel\": \"loose\" }"
  mermaidZoom = true
  [params.siteparam.test]
    text = "A **nested** parameter <b>with</b> formatting"
  [params.imageEffects]
    bg-white = true # extension, not supported by the theme
    border = false
    lightbox=false
